services:
  - type: web
    name: homen-api # Name of the service
    env: docker
    repo: https://github.com/IamHomen/HomenAPI.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000