services:
  - type: web
    name: natomanga-api # Name of the service
    env: docker
    repo: https://github.com/IamHomen/NatoMangaAPI.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000